name: Test on Multiple OS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [18, 20, 22]
        attempt: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Install build tools based on the OS
      - name: Install build tools (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 make g++

      - name: Install build tools (macOS)
        if: runner.os == 'macOS'
        run: |
          xcode-select --install || echo "Xcode tools already installed"

      - name: Install build tools (Windows)
        if: runner.os == 'Windows'
        run: |
          npm install -g windows-build-tools --vs2015 || echo "Windows build tools already installed"

      - name: Install dependencies
        run: npm install

      - name: Testing on OS (${{ matrix.os }}) with Node.js (version ${{ matrix.node-version }}) attempt ${{ matrix.attempt }}
        run: |
          echo "Run attempt: ${{ matrix.attempt }}"
          npm test
