name: Test on Multiple OS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [18, 20, 22]
        attempt: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Install build tools based on the OS
      - name: Install Python 3.10 (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo add-apt-repository ppa:deadsnakes/ppa -y
          sudo apt-get update
          sudo apt-get install -y python3.10 make g++ build-essential
          sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1
          python3 --version

      - name: Ensure build tools (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install python@3.11
          echo "PYTHON=$(which python3)" >> $GITHUB_ENV

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          npm config set msvs_version 2019
          npm install --fallback-to-build

        
      - name: Install dependencies
        run: npm install

      - name: Testing on OS (${{ matrix.os }}) with Node.js (version ${{ matrix.node-version }}) attempt ${{ matrix.attempt }}
        run: |
          echo "Run attempt: ${{ matrix.attempt }}"
          npm test
